### ISSUE TITLE
Error setStopLoss

### ISSUE THREAD

**Issue by eritondev-stack** [Reiryoku-Technologies/Mida#70]
Hello, how are you? I have error in my code, when I try set stop loss, follow error below:

![Captura de tela 2022-08-19 152909](https://user-images.githubusercontent.com/58184733/185683970-8b28e97a-adb3-4830-89e5-379583f58fdc.png)

you can help me?

Thanks!

**Comment by Vasile-Peste** [comment]
Hi! What version of Mida are you using? You are using Mida with cTrader? In that case what version of the plugin are you using?

**Comment by eritondev-stack** [comment]
![image](https://user-images.githubusercontent.com/58184733/185695399-dc59f093-254f-4a27-9a39-e04fc549b68d.png)

**Comment by eritondev-stack** [comment]
Yes, I'm using mida with Ctrader! 

![image](https://user-images.githubusercontent.com/58184733/185768071-162ec34a-2879-45af-86ee-9d13c20f4915.png)

**Comment by Vasile-Peste** [comment]
Thank you for letting me know! I'm investigating. In the meanwhile you can try using `changeProtection()` instead of `setStopLoss()` and let me know if the issue persists? Thank you!

- **Example**
```javascript
const stop = 1.01045;

await position.changeProtection({ stopLoss: stop, });
```

**Comment by eritondev-stack** [comment]
Vasile, I use "changeProtection", I work to me!!! Fix error it.

Thanks for helping!!!

**Comment by vanillamasonry** [comment]
Salut, problema nu este inca rezolvata cu setStopLoss  si la fel cu changeProtection.
Daca nu este valida valoare atunci functia ingheata si nu intoarce MidaProtectionChangeStatus.REJECTED.
Nu se poate sterge protectia valoare cu undefined, - nu am incercat cu takeProfit  dar banuiesc ca va fi aceasi eoare.

Utilizez (incerc) ultima versiune de cTrader plugin

Multumesc anticipat.

**Comment by Vasile-Peste** [comment]
Hello, thank you for your reports and patience. The issues have been fixed with [Mida 2022.5](https://github.com/Reiryoku-Technologies/Mida/releases/tag/v2022.5.0) and [Mida cTrader 5.3.1](https://github.com/Reiryoku-Technologies/Mida-cTrader/releases/tag/v5.3.1), can you please update both dependencies and let me know if everything works as expected?
Thank you!

**Comment by vanillamasonry** [comment]
Thank you for update and for your fast reply!
I have tested this new version and I have found that now MidaProtectionChangeStatus.REJECTED is triggered but I am still unable to delete stopLoss.
can give one example how to delete SL/TP ?

const stop = undefined; or 
const stop = 'undefined';

await position.changeProtection({ stopLoss: stop, });
or 
await position.setStopLoss(stop);

is not working -> MidaProtectionChangeStatus.REJECTED is triggered (before was freezing)

Thanks again

**Comment by Vasile-Peste** [comment]
> Thank you for update and for your fast reply! I have tested this new version and I have found that now MidaProtectionChangeStatus.REJECTED is triggered but I am still unable to delete stopLoss. can give one example how to delete SL/TP ?
> 
> const stop = undefined; or const stop = 'undefined';
> 
> await position.changeProtection({ stopLoss: stop, }); or await position.setStopLoss(stop);
> 
> is not working -> MidaProtectionChangeStatus.REJECTED is triggered (before was freezing)
> 
> Thanks again

I think that you are getting a rejected response just because you already don't have a SL set.
You are using the correct way

```javascript
await position.changeProtection({ stopLoss: undefined, });
// or
await position.setStopLoss(undefined);
```

But if your position stop loss is already undefined then the server will reject the protection change since there is nothing to change. Make sure that you have already set a SL before clearing it, anyway even if you get a rejected response in this case it has no actual impact on your code or position.

**Comment by vanillamasonry** [comment]
I'm sorry, I thought I was clear when I said that SL is not deleted. Obviously I was referring to an existing position with SL set.
On the other hand I must specify that my nodeJS  run under windows. I have seen differences between unix systems and windows. For example onTick in unix return values ended with 'd' character. 

To recap: 

Step 1.
const stop = 1.2; // a valid stop losss
await position.changeProtection({ stopLoss: stop, });  //  SL changed by system (verified with cTrader UI)

Step 2.
const stop = undefined; // system must remove SL !!!
await position.changeProtection({ stopLoss: stop, });  // SL not changed by the system  (verified with cTrader UI)

Thanks again

**Comment by Vasile-Peste** [comment]
> I'm sorry, I thought I was clear when I said that SL is not deleted. Obviously I was referring to an existing position with SL set. On the other hand I must specify that my nodeJS run under windows. I have seen differences between unix systems and windows. For example onTick in unix return values ended with 'd' character.
> 
> To recap:
> 
> Step 1. const stop = 1.2; // a valid stop losss await position.changeProtection({ stopLoss: stop, }); // SL changed by system (verified with cTrader UI - https://ctrader.com/download/)
> 
> Step 2. const stop = undefined; // system must remove SL !!! await position.changeProtection({ stopLoss: stop, }); // SL not changed by the system (verified with cTrader UI) MidaProtectionChangeStatus.REJECTED triggered
> 
> Thanks again

Hello,
I'm sorry but I'm unable to reproduce this issue,
may I know on what market you are trying and the broker name?

Thank you!
